config/routes.rb
Rails.application.routes.draw do
  root 'registers#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users
  resources :registers
  resources :hashtags
  resources :comments do
    collection {get :search, to: "comments#index"}
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  has_many :hashtags
  
  after_create :save_hashtags

  def find_hashtags
    content.split(" ").select{|word| word[0]=="#" && word[1]!="#"}
  end

  private
  def save_hashtags
    find_hashtags.each do |hashtag|
      self.hashtags.create(value: hashtag) unless self.hashtags.map(&:value).include? hashtag
    end
  end
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  belongs_to :comment
end

app/models/register.rb
class Register < ActiveRecord::Base
  validates :value, presence: true, length: {minimum: 2}
  after_create :update_fetch_data

  def recent_comments
    Comment.ransack(content_cont: value).result
  end

  def instagrammers
    instagrammers_hash = {}
    users = recent_comments.map(&:user)
    users.each do |user|
      instagrammers_hash[user.username] = user.comments
                                        .map(&:hashtags)
                                        .flatten.select{|i| i.value.include? value}
                                        .count
    end
    instagrammers_hash.sort_by {|_key, value| value}.reverse.to_h
  end

  private
  def update_fetch_data
    FetchCommentsWorker.perform_async self.id
  end
end

app/models/user.rb
# class User < ActiveRecord::Base
#   # Include default devise modules. Others available are:
#   # :confirmable, :lockable, :timeoutable and :omniauthable
#   devise :database_authenticatable, :registerable,
#          :recoverable, :rememberable, :trackable, :validatable
#   has_many :comments
#   mount_uploader :avatar, AvatarUploader
# end
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:instagram]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = "#{auth.uid}@gmail.com"
      user.username = auth.info[:nickname]
      user.provider = auth.provider
      user.uid = auth.uid
      user.profile_image = auth.info[:image]
      user.password = Devise.friendly_token[0,20]
    end
  end
  has_many :comments
  mount_uploader :avatar, AvatarUploader
end

# <OmniAuth::AuthHash expires=false token="2734684683.ed634b0.5fcff3a6ff4e4fd5965b97fb6ac0dec9">extra=
#<OmniAuth::AuthHash raw_info=
#<OmniAuth::AuthHash bio="" full_name="Tranthuc" id="2734684683"
# profile_picture="https://igcdn-photos-e-a.akamaihd.net/hphotos-ak-xft1/t51.2885-19/11906329_960233084022564_1448528159_a.jpg"
# username="tranthuc6685" website="">> info=#<OmniAuth::AuthHash::InfoHash bio="" email=nil
# image="https://igcdn-photos-e-a.akamaihd.net/hphotos-ak-xft1/t51.2885-19/11906329_960233084022564_1448528159_a.jpg" name="Tranthuc" nickname="tranthuc6685" website=""> provider="instagram" uid="2734684683">

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def instagram
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :authenticate_user!
  def show
    @register = Register.find params[:id]
    @instagrammers = eval(@register.fetch_data)[:instagrammers].first 10
    @recent_comments = Kaminari.paginate_array(eval(@register.fetch_data)[:recent_comments])
      .page(params[:page]).per 10
  end

  def index
    @register = Register.new
    @registers = Register.all
  end

  def create
    @register = Register.new register_params
    @register.value.insert(0, "#") if @register.value[0] != "#"
    @register.save
    redirect_to :back
  end

  private
  def register_params
    params.require(:register).permit :value
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def instagrammer user_id
    User.find(user_id).username
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Instagram Logo", root_path, class:"navbar-brand" %>
    </div>
    <div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.username, root_path %></li>
          <li><%= image_tag(current_user.profile_image, size: "40x40") %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HiworldTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/registers/_form.html.erb
<%= form_for @register do |f| %>
  <%= f.text_field :value %>
  <%= f.submit "Register" %>
<% end %>

app/views/registers/_recent_comments.html.erb
<div style="margin-top: 50px">
  <h2>Recent comments</h2>
  <span><%= paginate @recent_comments %></span>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th>Commented date</th>
      </tr>
    </thead>
    <tbody>
      <% @recent_comments.each do |comment| %>
        <tr>
          <td><%= instagrammer(comment[:user_id]) %></td>
          <td class="comment-content"><%= comment[:content] %></td>
          <td><%= comment[:created_at] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registers/_top_users.html.erb
<div style="margin-top: 50px">
  <h2>Top commented Instagrammer</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Index</th>
        <th>User</th>
        <th>Comment count</th>
      </tr>
    </thead>
    <tbody>
      <% @instagrammers.each_with_index do |(key, value), index| %>
        <tr>
          <td><%= "#{index+1}" %></td>
          <td><%= key %></td>
          <td><%= value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registers/index.html.erb
<div>
  <h2>Hashtags</h2>
  <%= render "registers/form" %>
</div>
<div style="margin-top: 50px">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Hashtag</th>
        <th>Count</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
      <% @registers.each do |register| %>
        <tr>
          <td><%= register.value %></td>
          <td><%= register.fetch_data? ? eval(register.fetch_data)[:amount] : "fetching..." %></td>
          <td><%= link_to_if(register.fetch_data?, "Show", register_path(register)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registers/show.html.erb
<div>
  <h2>Hashtags <span id="register-value"><%= @register.value %></span></h2>
</div>
<%= render "top_users" %>
<%= render "recent_comments" %>